services:
  db:
    image: postgres:16-alpine
    container_name: attendance-db
    environment:
      POSTGRES_USER: nextjs_app
      POSTGRES_PASSWORD: nextjs_pass
      POSTGRES_DB: nextjs_db
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: attendance-web
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "5555:5555"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
volumes:
  dbdata:
